# Generated by Django 4.0.6 on 2022-07-25 03:58

from django.db import migrations


def populate_sections(apps, schemaeditor):
    sections = {
        "front_page": "A department tasked with writing front page sections",
        "sports": "A department tasked with writing sports sections",
        "society": "A department tasked with writing society-related sections",
        "business": "A department tasked with writing business-related sections",
        "politics": "A department tasked with writing political sections",            
        "classified": "A department tasked with reviewing and publishing classified ads"
    }
    Section = apps.get_model("articles", "Section")
    for name, desc in sections.items():
        section_obj = Section(name=name, description=desc)
        section_obj.save()

def populate_article_types(apps, schemaeditor):
    art_types = {
        "articles": "Original research manuscripts",
        "brief_report": "Short, observational studies",
        "editorial": "Opinion piece",
        "column": "An opiniated piece on a specific topic",
    }
    ArticleType = apps.get_model("articles", "Articletype")
    for name, desc in art_types.items():
        art_obj = ArticleType(name=name, description=desc)
        art_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_sections),
        migrations.RunPython(populate_article_types),
    ]
