# Generated by Django 4.0.6 on 2022-07-25 05:31

from django.db import migrations


def populate_status(apps, schemaeditor):
    status = {
        "published": "Article has been published on the site",
        "pending review": "Article not validated by editor",
        "revision requested": "Articles that requires changes",
        "denied": "Articles that will not be published in site",
        "draft": "Articles not ready for review"
    }
    Status = apps.get_model("articles", "Status")
    for name, desc in status.items():
        sta_obj = Status(name=name, description=desc)
        sta_obj.save()



class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_status_article_status'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
